import { type El, type WorkspaceNamespace } from '../shared.js';

export interface CanonEventShape { id: string; seq: number; storyTime: string; kind: string; summary: string; detail?: string; location?: string; supersededBy?: string | null; [key: string]: unknown; }
export interface CanonLayerState { readonly status: 'loading' | 'ready' | 'error'; readonly events: CanonEventShape[]; readonly message?: string; }
export interface CanonEditor { selectedId: string | undefined; proposalId: string | undefined; draft: { storyTime: string; summary: string; detail: string }; dirty: boolean; error: string; }
export interface CanonEditOps { select(event: CanonEventShape): void; mutate(update: (draft: CanonEditor['draft']) => CanonEditor['draft']): void; propose(): void; accept(): void; }
export function canonCorrectionInput(draft: CanonEditor['draft']): unknown { return { storyTime: draft.storyTime, summary: draft.summary, detail: draft.detail, participants: [], location: '', consequences: [], affectedLayers: [] }; }

export function canonLayer(h: El, _projectId: string, _workspace: WorkspaceNamespace | undefined, layerState: CanonLayerState, editor: CanonEditor, ops: CanonEditOps): unknown {
  if (layerState.status === 'loading') return h('section', { className: 'nv-panel', 'data-novel-layer-panel': 'canon', 'data-novel-layer-state': 'loading' }, '\u6b63\u5728\u88c5\u8f7d\u6b63\u53f2\u8d26\u672c\u2026');
  if (layerState.status === 'error') return h('section', { className: 'nv-panel', 'data-novel-layer-panel': 'canon', 'data-novel-layer-state': 'error', role: 'alert' }, layerState.message ?? '\u6b63\u53f2\u8d26\u672c\u8bfb\u53d6\u5931\u8d25');
  const selected = layerState.events.find((event) => event.id === editor.selectedId);
  const activeCount = layerState.events.filter((event) => event.supersededBy === null || event.supersededBy === undefined).length;
  const list = h('div', { className: 'nv-editor__list', role: 'list' }, h('div', { className: 'nv-editor__toolbar' }, h('span', { className: 'nv-state__hint' }, `\u5171 ${layerState.events.length} \u6761 \u00b7 \u6709\u6548 ${activeCount}`)), layerState.events.map((event) => h('button', { key: event.id, type: 'button', role: 'listitem', className: 'nv-editor__item' + (editor.selectedId === event.id ? ' is-active' : ''), 'data-novel-canon-id': event.id, onClick: () => ops.select(event) }, `${event.seq} \u00b7 ${event.summary}${event.supersededBy ? '\uff08\u5df2\u66f4\u6b63\uff09' : ''}`)));
  const detail = h('div', { className: 'nv-editor__detail' },
    h('div', { className: 'nv-canon__readonly', 'data-novel-canon-readonly': '', role: 'note' }, '\u53ea\u8bfb\u8d26\u672c \u00b7 \u66f4\u6b63\u7ecf ConfirmationGate'),
    h('h3', { className: 'nv-editor__title' }, selected === undefined ? '\u6b63\u53f2\u8d26\u672c' : `\u6b63\u53f2 ${selected.seq} \u00b7 ${selected.summary}`),
    selected === undefined ? h('p', { className: 'nv-outline__nodetail' }, '\u4ece\u5de6\u4fa7\u9009\u62e9\u4e00\u4e2a\u6b63\u53f2\u4e8b\u4ef6\uff0c\u53ef\u53d1\u8d77 supersede \u66f4\u6b63\u3002') : h('div', { className: 'nv-form' }, h('p', { className: 'nv-field__label' }, `\u7c7b\u578b ${selected.kind} \u00b7 \u65f6\u95f4 ${selected.storyTime} \u00b7 \u5730\u70b9 ${selected.location ?? '\u2014'}`), selected.detail ? h('p', { className: 'nv-canon__detail' }, selected.detail) : null, selected.supersededBy ? h('p', { className: 'nv-editor__badge', 'data-novel-canon-superseded': '' }, `\u5df2\u88ab ${selected.supersededBy} \u66f4\u6b63`) : null, h('h4', { className: 'nv-outline__subtitle' }, '\u53d1\u8d77 supersede \u66f4\u6b63'), h('label', { className: 'nv-field' }, h('span', { className: 'nv-field__label' }, '\u66f4\u6b63\u65f6\u95f4'), h('input', { type: 'text', className: 'nv-field__input', value: editor.draft.storyTime, onChange: (event: { target: { value: string } }) => ops.mutate((draft) => ({ ...draft, storyTime: event.target.value })) })), h('label', { className: 'nv-field' }, h('span', { className: 'nv-field__label' }, '\u66f4\u6b63\u6458\u8981'), h('input', { type: 'text', className: 'nv-field__input', value: editor.draft.summary, onChange: (event: { target: { value: string } }) => ops.mutate((draft) => ({ ...draft, summary: event.target.value })) })), h('label', { className: 'nv-field' }, h('span', { className: 'nv-field__label' }, '\u66f4\u6b63\u8be6\u60c5'), h('textarea', { className: 'nv-field__input', rows: 3, value: editor.draft.detail, onChange: (event: { target: { value: string } }) => ops.mutate((draft) => ({ ...draft, detail: event.target.value })) }))),
    h('div', { className: 'nv-editor__actions' }, editor.proposalId !== undefined ? h('button', { type: 'button', className: 'nv-btn nv-btn--primary', 'data-novel-canon-accept': '', onClick: ops.accept }, '\u786e\u8ba4\u66f4\u6b63\uff08\u8ffd\u52a0 supersede\uff09') : h('button', { type: 'button', className: 'nv-btn nv-btn--primary', 'data-novel-canon-propose': '', onClick: ops.propose, disabled: editor.selectedId === undefined || !editor.dirty }, '\u53d1\u8d77\u66f4\u6b63\u63d0\u6848')),
    editor.error ? h('p', { className: 'nv-editor__error', 'data-novel-error': 'canon', role: 'alert' }, editor.error) : null,
  );
  return h('section', { className: 'nv-editor', 'data-novel-layer-panel': 'canon', 'data-novel-layer-state': 'ready' }, h('div', { className: 'nv-editor__columns' }, list, detail));
}
