import { type El, type WorkspaceNamespace } from '../shared.js';
import { authorEnumLabel, toUserMessage } from '../presentation.js';
import { renderSaveStatus, saveButtonLabel, saveStatusLine } from '../save-status.js';

export interface CanonEventShape { id: string; seq: number; storyTime: string; kind: string; summary: string; detail?: string; location?: string; supersededBy?: string | null; [key: string]: unknown; }
export interface CanonLayerState { readonly status: 'loading' | 'ready' | 'error'; readonly events: CanonEventShape[]; readonly message?: string; }
export interface CanonEditor { selectedId: string | undefined; proposalId: string | undefined; draft: { storyTime: string; summary: string; detail: string }; dirty: boolean; error: string; saving: boolean; saveMessage: string; }
export interface CanonEditOps { select(event: CanonEventShape): void; mutate(update: (draft: CanonEditor['draft']) => CanonEditor['draft']): void; propose(): void; accept(): void; }
export function canonCorrectionInput(draft: CanonEditor['draft'], targetId: string): Parameters<WorkspaceNamespace['canonCorrectionPropose']>[2] { return { id: `evt-fix-${targetId}`, storyTime: draft.storyTime, summary: draft.summary, detail: draft.detail, participants: [], location: '', consequences: [], affectedLayers: [] }; }

export function canonLayer(h: El, _projectId: string, _workspace: WorkspaceNamespace | undefined, layerState: CanonLayerState, editor: CanonEditor, ops: CanonEditOps): unknown {
  if (layerState.status === 'loading') return h('section', { className: 'nv-panel', 'data-novel-layer-panel': 'canon', 'data-novel-layer-state': 'loading' }, '正在装载正史账本…');
  if (layerState.status === 'error') return h('section', { className: 'nv-panel', 'data-novel-layer-panel': 'canon', 'data-novel-layer-state': 'error', role: 'alert' }, layerState.message ?? '正史账本读取失败');
  const selected = layerState.events.find((event) => event.id === editor.selectedId);
  const activeCount = layerState.events.filter((event) => event.supersededBy === null || event.supersededBy === undefined).length;
  const list = h('div', { className: 'nv-editor__list', role: 'list' }, h('div', { className: 'nv-editor__toolbar' }, h('span', { className: 'nv-state__hint' }, `共 ${layerState.events.length} 条 · 有效 ${activeCount}`)), layerState.events.map((event) => h('button', { key: event.id, type: 'button', role: 'listitem', className: 'nv-editor__item' + (editor.selectedId === event.id ? ' is-active' : ''), 'data-novel-canon-id': event.id, onClick: () => ops.select(event) }, `${event.seq} · ${event.summary}${event.supersededBy ? '（已更正）' : ''}`)));
  const detail = h('div', { className: 'nv-editor__detail' },
    h('div', { className: 'nv-canon__readonly', 'data-novel-canon-readonly': '', role: 'note' }, '只读账本 · 更正需要一次明确确认'),
    h('h3', { className: 'nv-editor__title' }, selected === undefined ? '正史账本' : `正史 ${selected.seq} · ${selected.summary}`),
    selected === undefined ? h('p', { className: 'nv-outline__nodetail' }, '从左侧选择一个正史事件，可发起修订。') : h('div', { className: 'nv-form' }, h('p', { className: 'nv-field__label' }, `类型 ${authorEnumLabel(selected.kind)} · 时间 ${selected.storyTime} · 地点 ${selected.location ?? '—'}`), selected.detail ? h('p', { className: 'nv-canon__detail' }, selected.detail) : null, selected.supersededBy ? h('p', { className: 'nv-editor__badge', 'data-novel-canon-superseded': '' }, '已有后续修订') : null, h('h4', { className: 'nv-outline__subtitle' }, '发起修订'), h('label', { className: 'nv-field' }, h('span', { className: 'nv-field__label' }, '更正时间'), h('input', { type: 'text', className: 'nv-field__input', value: editor.draft.storyTime, onChange: (event: { target: { value: string } }) => ops.mutate((draft) => ({ ...draft, storyTime: event.target.value })) })), h('label', { className: 'nv-field' }, h('span', { className: 'nv-field__label' }, '更正摘要'), h('input', { type: 'text', className: 'nv-field__input', value: editor.draft.summary, onChange: (event: { target: { value: string } }) => ops.mutate((draft) => ({ ...draft, summary: event.target.value })) })), h('label', { className: 'nv-field' }, h('span', { className: 'nv-field__label' }, '更正详情'), h('textarea', { className: 'nv-field__input', rows: 3, value: editor.draft.detail, onChange: (event: { target: { value: string } }) => ops.mutate((draft) => ({ ...draft, detail: event.target.value })) }))),
    h('div', { className: 'nv-editor__actions' }, editor.proposalId !== undefined ? h('button', { type: 'button', className: 'nv-btn nv-btn--primary', 'data-novel-canon-accept': '', onClick: ops.accept, disabled: editor.saving }, saveButtonLabel(editor.saving, '确认追加修订')) : h('button', { type: 'button', className: 'nv-btn nv-btn--primary', 'data-novel-canon-propose': '', onClick: ops.propose, disabled: editor.selectedId === undefined || !editor.dirty || editor.saving }, saveButtonLabel(editor.saving, '发起修订'))),
    renderSaveStatus(h, saveStatusLine(editor.saving, editor.saveMessage, editor.error), 'canon'),
    editor.error ? h('p', { className: 'nv-editor__error', 'data-novel-error': 'canon', role: 'alert' }, toUserMessage(editor.error)) : null,
  );
  return h('section', { className: 'nv-editor', 'data-novel-layer-panel': 'canon', 'data-novel-layer-state': 'ready' }, h('div', { className: 'nv-editor__columns' }, list, detail));
}
