import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createLocalizedEditService, type ReparseRequest } from './edit-service.js';
import { TextRepository } from '../core/text/index.js';
import { ConfirmationGate } from '../core/confirm/index.js';

const roots: string[] = [];
const settings = { modelRef: 'dsh/default', credentialRef: 'dsh/managed' };
async function setup() { const root = await mkdtemp(join(tmpdir(), 'novel-i42-')); roots.push(root); const repository = new TextRepository(join(root, 'projects', 'demo')); await repository.open(); await repository.createChapter({ id: 'chapter-1', index: 1, title: 'Chapter', pov: 'lin', status: 'draft' }); await repository.appendScene('chapter-1', { id: 'scene-1', content: 'prefix TARGET suffix', summary: 'summary', beats: [], canonEvents: [], notes: '' }); return root; }
afterEach(async () => Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))));
function llm() { return { async *stream() { yield { type: 'text-delta', text: 'rewritten' }; yield { type: 'finish', reason: { kind: 'stop' } }; } }; }
function request(root: string, id: string, calls: string[]): ReparseRequest { return { id, projectId: 'demo', chapterId: 'chapter-1', sceneId: 'scene-1', range: { start: 7, end: 13 }, replacement: 'parsed', parsers: { c2: async () => { calls.push('parse:c2'); return 'c2'; }, c1: async () => { calls.push('parse:c1'); return 'c1'; }, c3: async () => { calls.push('parse:c3'); return 'c3'; }, c4: async () => { calls.push('parse:c4'); return 'c4'; }, b2: async () => { calls.push('parse:b2'); return 'b2'; } }, writers: { c2: async () => { calls.push('write:c2'); }, c1: async () => { calls.push('write:c1'); }, c3: async () => { calls.push('write:c3'); }, c4: async () => { calls.push('write:c4'); }, b2: async () => { calls.push('write:b2'); } } }; }
describe('I42 localized edit service', () => {
  it('persists exact selected-range edits and reports target-scene hashes', async () => { const root = await setup(); const service = createLocalizedEditService(llm(), join(root, 'projects')); await service.open('demo'); const result = await service.edit('demo', 'chapter-1', 'scene-1', { start: 7, end: 13 }, 'replacement'); expect(result.scene.content).toBe('prefix replacement suffix'); expect(result.evidence.before).not.toBe(result.evidence.after); expect(result.evidence.unchangedPrefix).toBe('prefix '); expect(result.evidence.unchangedSuffix).toBe(' suffix'); });
  it('keeps original text when rewrite is rejected', async () => { const root = await setup(); const service = createLocalizedEditService(llm(), join(root, 'projects')); await service.open('demo'); const result = await service.rewrite('demo', 'chapter-1', 'scene-1', { start: 7, end: 13 }, 'rewrite', settings, 'reject'); expect(result.applied).toBe(false); const repository = new TextRepository(join(root, 'projects', 'demo')); await repository.open(); expect((await repository.readChapter('chapter-1')).scenes[0].content).toBe('prefix TARGET suffix'); });
  it('does not parse or write before Gate acceptance, then fans out and writes in order', async () => { const root = await setup(); const service = createLocalizedEditService(llm(), join(root, 'projects')); await service.open('demo'); const calls: string[] = []; const edit = request(root, 'reparse-1', calls); const pending = await service.proposeReparse(edit); expect(pending.status).toBe('pending'); await expect(service.applyAcceptedReparse(edit)).rejects.toThrow(/accepted ConfirmationGate/); expect(calls).toEqual([]); const gate = await ConfirmationGate.open(join(root, 'projects', 'demo')); await gate.accept('reparse-1'); const result = await service.applyAcceptedReparse(edit); expect(result.status).toBe('written'); expect(calls).toEqual(['parse:c2', 'parse:c1', 'parse:c3', 'parse:c4', 'parse:b2', 'write:c2', 'write:c1', 'write:c3', 'write:c4', 'write:b2']); const repository = new TextRepository(join(root, 'projects', 'demo')); await repository.open(); expect((await repository.readChapter('chapter-1')).scenes[0].content).toBe('prefix parsed suffix'); });
});
