import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

/**
 * I2 client bundle build (design §0.1.3 I2, H0-9): produces the package's
 * browser half `lib/client.js` from `src/client.ts` using esbuild — a public,
 * published bundler — NOT an internal DSH builder and NOT `clientBundle`.
 *
 * The output follows the public `@deepseek-ai/dsh-client-modules@0.1.0-rc.7`
 * wire contract: a classic script that calls
 * `window.__ModuleLoader__.load({ id, factory })` with a closure factory that
 * returns the client plugin entry. `react` stays external — the DSH client
 * module table resolves it at runtime, so the bundle carries no React copy.
 */
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');

const packageName = 'novel-creation-tool';

const result = await build({
  entryPoints: [resolve(repoRoot, 'src/client.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  external: ['react'],
  write: false,
  logLevel: 'silent',
});

const body = result.outputFiles[0].text;

// Handoff wrapper: declare the CJS locals the esbuild output closes over, then
// hand the module table's sync `require` to the bundle's default factory.
const bundle = [
  '/* GENERATED by scripts/build-client.mjs — do not edit. */',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(packageName)},`,
  '  factory: (require) => {',
  '    const module = { exports: {} };',
  '    const exports = module.exports;',
  body,
  '    return module.exports.default(require);',
  '  },',
  '});',
  '',
].join('\n');

const outDir = resolve(repoRoot, 'lib');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'client.js'), bundle);

console.log(`I2 client bundle: lib/client.js (${Buffer.byteLength(bundle)} bytes)`);
