import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

import { build } from 'esbuild';

/**
 * I2 client bundle build (design §0.1.3 I2, H0-9): produces the package's
 * browser half `lib/client.js` from `src/client.ts` using esbuild — a public,
 * published bundler — NOT an internal DSH builder and NOT `clientBundle`.
 *
 * The output follows the public `@deepseek-ai/dsh-client-modules@0.1.1-rc.2`
 * wire contract (I85 baseline): a classic script that calls
 * `window.__ModuleLoader__.load({ id, factory })` with a closure factory that
 * returns the client plugin entry. `react` stays external — the DSH client
 * module table resolves it at runtime, so the bundle carries no React copy.
 *
 * Build-race fix（live-profile HMR 场景）: `src/client.ts` is excluded from
 * `tsconfig.build.json`, so `tsc` never emits `lib/client.js` (its NodeNext
 * output was ESM and briefly sat on disk before this script overwrote it —
 * a live DSH web server hot-loading that window threw
 * "Cannot use import statement outside a module"). `lib/client.js` is now
 * written exclusively here. The declaration pass below restores
 * `lib/client.d.ts` (+ the `lib/client/` type tree), which is the
 * `exports["./client"].types` contract, from the same source.
 */
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');

const packageName = 'novel-creation-tool';

const result = await build({
  entryPoints: [resolve(repoRoot, 'src/client.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  external: ['react'],
  write: false,
  logLevel: 'silent',
});

const body = result.outputFiles[0].text;

// 1) Declaration-only emit first: lib/client.d.ts + lib/client/*.d.ts. If it
//    fails, lib/client.js keeps its previous (last good) wrapper content.
const tscBin = resolve(repoRoot, 'node_modules', '.bin', process.platform === 'win32' ? 'tsc.cmd' : 'tsc');
const decl = spawnSync(tscBin, ['-p', 'tsconfig.build-client.json'], { cwd: repoRoot, encoding: 'utf8' });
if (decl.status !== 0) {
  process.stderr.write(decl.stdout || '');
  process.stderr.write(decl.stderr || '');
  throw new Error('client declaration emit (tsconfig.build-client.json) failed; lib/client.js was not rewritten');
}

// 2) Handoff wrapper: declare the CJS locals the esbuild output closes over,
//    then hand the module table's sync `require` to the bundle's default
//    factory. Written last so lib/client.js only ever holds this classic form.
const bundle = [
  '/* GENERATED by scripts/build-client.mjs — do not edit. */',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(packageName)},`,
  '  factory: (require) => {',
  '    const module = { exports: {} };',
  '    const exports = module.exports;',
  body,
  '    return module.exports.default(require);',
  '  },',
  '});',
  '',
].join('\n');

const outDir = resolve(repoRoot, 'lib');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'client.js'), bundle);

console.log(`I2 client bundle: lib/client.js (${Buffer.byteLength(bundle)} bytes)`);
