import assert from 'node:assert/strict';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { launchUiElectron } from './ui-electron-session.mjs';
import { uiInvoke } from './ui-test-provider.mjs';

const app = await launchUiElectron('i208');
const invoke = (method, ...args) => uiInvoke(app, method, ...args);
try {
  await app.fill('[data-novel-project-name-input]', '细纲绑定验收');
  await app.click('[data-novel-project-create]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")', 'project');
  const id = (await invoke('novelWorkspace/projectList'))[0].id;
  await invoke('novelWorkspace/outlineSave', id, { id: 'outline', structure: 'free', logline: '调查', themes: [], acts: [{ id: 'act', index: 0, title: '雨夜', goal: '调查', beats: [{ id: 'beat', title: '调查', description: '寻找线索', charactersInvolved: [], conflictType: 'external', prerequisites: [], optional: false, detailBeats: [{ id: 'card', title: '线索', summary: '找到线索', pov: 'hero', wordTarget: 100, points: [], status: 'writing' }] }] }], foreshadowing: [], endings: [] });
  const { fingerprint } = await invoke('novelText/fingerprint', id);
  const chapter = await invoke('novelText/chapterCreate', id, { id: 'chapter', index: 1, title: '第一章', pov: 'hero', status: 'draft', expectedFingerprint: fingerprint });
  await invoke('novelText/sceneCreate', id, { chapterId: 'chapter', index: 0, scene: { id: 'scene', content: '雨落在窗前。', summary: '雨夜开场', beats: [], canonEvents: [], notes: '' }, expectedFingerprint: chapter.fingerprint });
  const beforeText = (await invoke('novelText/fingerprint', id)).fingerprint;
  const outlinePath = join(app.profile, 'library', id, 'outline.yaml');
  const beforeOutline = await readFile(outlinePath, 'utf8');
  await app.send('Page.reload');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")', 'reopen');
  await app.click('[data-novel-nav-group="advanced"] > summary');
  await app.click('[data-novel-nav-item="chapters"]');
  await app.waitFor('!!document.querySelector("[data-novel-chapter-item]")', 'chapter');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.waitFor('!!document.querySelector("[data-novel-management-state=ready]")', 'management');
  await app.click('[data-novel-binding-save]');
  await app.waitFor('document.querySelector("[data-novel-binding-message]")?.textContent.includes("选中一个具体的正文场景")', 'missing scene feedback');
  assert.equal((await invoke('novelSceneOutlineBinding/read', id)).manual.length, 0);
  await app.screenshot('missing-selection');
  await app.click('[data-novel-chapter-item]');
  await app.waitFor('!!document.querySelector("[data-novel-scene-item]")', 'scene');
  await app.click('[data-novel-scene-item]');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.waitFor('!!document.querySelector("[data-novel-management-state=ready]")', 'scene management');
  await app.click('[data-novel-binding-save]');
  await app.waitFor('document.querySelector("[data-novel-binding-message]")?.textContent.includes("细纲目标")', 'missing card feedback');
  await app.evaluate(`(() => { const e=document.querySelector('[data-novel-entity-select="binding-target"]'); e.value='card'; e.dispatchEvent(new Event('change',{bubbles:true})); })()`);
  await app.click('[data-novel-binding-save]');
  await app.waitFor('document.querySelector("[data-novel-binding-message]")?.textContent==="细纲绑定已保存。"', 'binding saved');
  assert.match(await app.evaluate('document.querySelector("[data-novel-binding-state]").textContent'), /手动绑定 1 条；有效映射 1 条/);
  const binding = await invoke('novelSceneOutlineBinding/read', id);
  assert.deepEqual(binding.manual, [{ sceneId: 'scene', detailBeatId: 'card' }]);
  assert.equal(binding.effective[0].chapterId, 'chapter');
  const projectPath = join(app.profile, 'library', id);
  assert.match(await readFile(join(projectPath, 'scene-outline-bindings.yaml'), 'utf8'), /detailBeatId: card/);
  const events = (await readFile(join(projectPath, 'outline-generation-baselines.jsonl'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
  assert.ok(events.some(event => event.kind === 'create' && event.baseline.sceneId === 'scene' && event.baseline.detailBeatId === 'card'));
  assert.equal((await invoke('novelText/fingerprint', id)).fingerprint, beforeText);
  assert.equal(await readFile(outlinePath, 'utf8'), beforeOutline);
  await app.click('[data-novel-management-refresh]');
  await app.waitFor('!!document.querySelector("[data-novel-management-state=ready]")', 'readback');
  assert.match(await app.evaluate('document.querySelector("[data-novel-binding-state]").textContent'), /手动绑定 1 条；有效映射 1 条/);
  await app.screenshot('binding-saved');
  await writeFile(join(app.evidence, 'validation.json'), JSON.stringify({ passed: true, checks: ['missing scene/card feedback without writes', 'selected scene and writing card save via strict IPC', 'manual and effective counts are one', 'binding and matching baseline persisted locally', 'refresh retains binding', 'C5 and B5 unchanged'], files: await readdir(projectPath) }, null, 2));
  process.stdout.write('I208 Electron: missing selection feedback, explicit binding save and readback, unchanged prose/outline\n');
} finally { await app.close(); }
