import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { launchUiElectron } from './ui-electron-session.mjs';
import { startUiTestProvider, uiInvoke } from './ui-test-provider.mjs';

const provider = await startUiTestProvider();
const app = await launchUiElectron('i191');
const checks = [];
const check = (name, value) => { assert.ok(value, name); checks.push({ name, passed: true }); };
const invoke = (method, ...args) => uiInvoke(app, method, ...args);
try {
  await app.fill('[data-novel-project-name-input]', '北港长篇正文验收');
  await app.click('[data-novel-project-create]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")', 'created project');
  const projects = await invoke('novelWorkspace/projectList');
  const id = projects[0].id;
  await invoke('novelLlmConfig/save', { baseUrl: provider.endpoint, model: 'ui-deterministic', apiKey: 'test-only-not-a-real-key', maxTokens: 32768, thinking: 'disabled', reasoningEffort: 'low' });
  await invoke('novelWorkspace/characterCreate', id, { id: 'mira', name: '米拉', aliases: [], kind: 'protagonist', personality: '谨慎', background: '测绘师', motivation: '追查真相', goals: [], flaws: [], abilities: [], speechStyle: '', staticTraits: [], arc: { startingPoint: '', desiredEnd: '', keyBeats: [] }, relationships: [], knowledgeIds: [] });
  // Domain fixture setup is distinct from the author interactions tested below.
  const outline = { id: 'outline', structure: 'free', logline: '米拉追查北港旧灯塔的秘密。', themes: ['追查'], acts: [{ id: 'act-1', index: 0, title: '雨夜北港', goal: '找到线索', beats: [{ id: 'beat-1', title: '码头', description: '米拉找到钥匙。', charactersInvolved: ['mira'], conflictType: 'external', prerequisites: [], optional: false, detailBeats: [{ id: 'detail-1', title: '钥匙', summary: '米拉找到钥匙。', pov: 'mira', wordTarget: 100, points: ['钥匙'], status: 'planned' }] }] }], foreshadowing: [], endings: [] };
  await invoke('novelWorkspace/outlineSave', id, outline);
  await invoke('novelRuleStyleManager/saveStyle', id, { name: '克制', person: 'third-limited', tense: 'past', povScope: 'single', tone: '克制', proseStyle: '简洁', chapterFormat: 'plain', dialogueConventions: 'quotes', forbidden: [] });
  // Fixture only: C3 must already be initialized; this is not a source-import acceptance claim.
  await writeFile(join(app.profile, 'library', id, 'knowledge.yaml'), JSON.stringify({entries: [], states: [{characterId: 'mira', knows: []}]}), { flag: 'w' });
  await app.send('Page.reload');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")', 'reopen seeded fixture');
  await app.click('[data-novel-nav-group="advanced"] > summary');
  await app.click('[data-novel-nav-item="outline"]');
  await app.waitFor('!!document.querySelector("[data-novel-outline-add-act]")', 'outline');
  await app.click('[data-novel-outline-act="act-1"]');
  await app.click('[data-novel-outline-beat="beat-1"]');
  await app.click('[data-novel-detail-card="detail-1"]');
  await app.screenshot('outline');
  await app.fill('[data-novel-outline-detail-append] textarea', '增加调查潮痕的场景');
  await app.click('[data-novel-outline-detail-append-generate]');
  await app.waitFor('!!document.querySelector("[data-novel-outline-detail-candidate]")', 'outline candidate');
  await app.click('[data-novel-outline-detail-keep]');
  await app.waitFor('document.querySelector("[data-novel-outline-detail-keep]").getAttribute("aria-pressed")==="false"', 'skip settled');
  check('outline skip choice remains explicit', await app.evaluate('document.querySelector("[data-novel-outline-detail-keep]").getAttribute("aria-pressed")==="false"'));
  await app.click('[data-novel-outline-detail-keep]');
  await app.waitFor('document.querySelector("[data-novel-outline-detail-keep]").getAttribute("aria-pressed")==="true"', 'keep settled');
  await app.click('[data-novel-outline-detail-propose]');
  await app.waitFor('!!document.querySelector("[data-novel-outline-detail-accept]")', 'outline confirmation');
  await app.screenshot('outline-confirmation');
  await app.click('[data-novel-outline-detail-accept]');
  await app.waitFor('document.querySelectorAll("[data-novel-detail-card]").length===2', 'outline application');
  check('shipped outline generation reaches Main and explicit confirmation', true);
  await app.click('[data-novel-nav-item="chapters"]');
  await app.waitFor('!!document.querySelector("[data-novel-chapter-modes]")', 'chapters');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.waitFor('document.querySelector("[data-novel-chapter-management]")?.dataset.novelManagementState==="ready"', 'management ready');
  await app.fill('[data-novel-management-input="chapter-title"]', '雨夜的北港与未完成的海图');
  await app.evaluate(`(() => { const e=document.querySelector('[data-novel-entity-select="chapter-pov"]'); if(e){e.value='mira';e.dispatchEvent(new Event('change',{bubbles:true}));} })()`);
  await app.click('[data-novel-chapter-create]');
  await app.waitFor('!!document.querySelector("[data-novel-chapter-item]")', 'chapter created');
  await app.click('[data-novel-chapter-item]');
  await app.waitFor('!!document.querySelector("[data-novel-scene-create]")', 'scene form');
  await app.fill('[data-novel-management-input="scene-summary"]', '米拉在雨中寻找钥匙');
  await app.click('[data-novel-scene-create]');
  // Reload current chapter via its real navigation control after mutation.
  await app.waitFor('document.querySelector("[data-novel-chapter-management]")?.dataset.novelManagementState==="ready"', 'scene persisted');
  await app.click('[data-novel-chapter-item]');
  await app.waitFor('!!document.querySelector("[data-novel-scene-item]")', 'scene tree');
  check('scene navigation is nested within the chapter tree', await app.evaluate('!!document.querySelector("[data-novel-chapter-tree] [data-novel-chapter-scenes] [data-novel-scene-item]")'));
  await app.click('[data-novel-scene-item]');
  await app.click('[data-novel-chapter-mode="writing"]');
  await app.waitFor('!!document.querySelector("[data-novel-scene-edit]")', 'prose read');
  await app.click('[data-novel-scene-edit]');
  const prose = '雨落北港，米拉借着灯火辨认海图。'.repeat(90);
  await app.fill('[data-novel-scene-text]', prose);
  for (const width of [1440, 1024, 720, 440]) {
    await app.send('Emulation.setDeviceMetricsOverride', { width, height: 1000, deviceScaleFactor: 1, mobile: false });
    await app.evaluate('document.querySelector("[data-novel-scene-text]").scrollIntoView({block:"center"})');
    check(`long Chinese editor fits at ${width}`, await app.evaluate(`(() => { const e=document.querySelector('[data-novel-scene-text]'); const r=e.getBoundingClientRect(); return r.left>=0 && r.right<=innerWidth && e.scrollWidth<=e.clientWidth+1; })()`));
    await app.screenshot(`prose-${width}`);
  }
  await app.send('Emulation.clearDeviceMetricsOverride');
  await app.click('[data-novel-chapter-mode="candidate"]');
  await app.click('[data-novel-chapter-mode="writing"]');
  check('mode changes retain unsaved prose', await app.evaluate(`document.querySelector('[data-novel-scene-text]').value===${JSON.stringify(prose)}`));
  // Repeated navigation must not act as an implicit discard decision.
  await app.click('[data-novel-chapter-item]');
  await app.waitFor('!!document.querySelector("[data-novel-scene-leave]")', 'dirty leave guard');
  await app.click('[data-novel-chapter-item]');
  check('repeated navigation cannot bypass dirty protection', await app.evaluate(`document.querySelector('[data-novel-scene-text]').value===${JSON.stringify(prose)} && !!document.querySelector('[data-novel-scene-leave]')`));
  await app.click('[data-novel-scene-leave-cancel]');
  const chapterId = (await invoke('novelWorkspace/chapterList', id))[0].id;
  const sceneId = (await invoke('novelWorkspace/chapterRead', id, chapterId)).scenes[0].id;
  const hash = text => createHash('sha256').update(text).digest('hex');
  const external = '另一处已经保存的正文';
  await invoke('novelWorkspace/sceneEdit', id, chapterId, sceneId, {start:0,end:0}, external, hash(''));
  await app.click('[data-novel-scene-save]');
  await app.waitFor('!!document.querySelector("[data-novel-save-status=scene][role=alert]") || !!document.querySelector("[data-novel-scene-editor] [role=alert]")', 'CAS save refusal');
  check('save failure retains every character', await app.evaluate(`document.querySelector('[data-novel-scene-text]').value===${JSON.stringify(prose)}`));
  await app.screenshot('save-failure-retains-input');
  await invoke('novelWorkspace/sceneEdit', id, chapterId, sceneId, {start:0,end:external.length}, '', hash(external));
  await app.click('[data-novel-scene-save]');
  await app.waitFor('document.querySelector("[data-novel-scene-range]")?.dataset.novelSceneRange==="none"', 'saved prose');
  check('retry saves the preserved draft through Main CAS', (await invoke('novelWorkspace/sceneRead',id,chapterId,sceneId)).scene.content===prose);
  await app.click('[data-novel-chapter-mode="versions"]');
  await app.waitFor('document.querySelector("[data-novel-version-panel]")?.dataset.novelVersionState==="ready" && !!document.querySelector("[data-novel-scene-version-tools]")', 'version tools');
  await app.click('[data-novel-scene-version-tools] > summary');
  await app.waitFor('["ready","error"].includes(document.querySelector("[data-novel-branch-panel]")?.dataset.novelBranchState)', 'branch state');
  if (await app.evaluate('!!document.querySelector("[data-novel-branch-error]")')) throw new Error('Branch UI error: '+JSON.stringify(await app.evaluate(`window.novelDesktop.invoke('novel-creation-tool/novelBranches/list', ${JSON.stringify([id,chapterId,sceneId])})`)));
  await app.fill('input[data-novel-branch-label]', '雨夜初稿');
  await app.click('[data-novel-branch-save]');
  await app.waitFor('!!document.querySelector("[data-novel-branch-item]")', 'named version');
  await app.click('[data-novel-branch-diff]');
  await app.waitFor('!!document.querySelector("[data-novel-branch-diff-view]")', 'version diff');
  await app.screenshot('named-version-diff');
  check('named version and diff are reachable from versions mode', true);
  await app.click('[data-novel-chapter-mode="candidate"]');
  await app.fill('[data-novel-candidate-rewrite-prompt]', '保留事实，压缩文字。');
  await app.click('[data-novel-candidate-propose-rewrite]');
  await app.waitFor('!!document.querySelector("[data-novel-candidate-review], [data-novel-candidate-error]")', 'candidate result');
  check('real Main provider pipeline produces review', await app.evaluate('!!document.querySelector("[data-novel-candidate-review]")'));
  await app.screenshot('candidate-review');
  await app.click('[data-novel-candidate-adopt-draft]');
  await app.waitFor('document.querySelector("[data-novel-writing-workflow-state=saved]")!==null', 'draft accepted');
  await app.click('[data-novel-chapter-mode="writing"]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-prepare]")', 'finalization');
  await app.click('[data-novel-finalization-prepare]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-propose], [data-novel-finalization-message]")', 'finalization analysis');
  await app.click('[data-novel-finalization-propose]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-pending]")', 'confirmation gate');
  await app.screenshot('finalization-confirmation');
  await app.click('[data-novel-finalization-accept]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-complete]")', 'finalization applied');
  check('candidate adoption and separate I11 finalization complete', true);
  await app.screenshot('finalization-complete');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.click('[data-novel-scene-delete]');
  await app.waitFor('!!document.querySelector("[data-novel-deletion-impact]")', 'delete impact');
  check('delete impact lists prose and versions before confirmation', await app.evaluate('document.querySelector("[data-novel-deletion-impact]").textContent.includes("分支")'));
  if (await app.evaluate('!!document.querySelector("[data-novel-deletion-reject-candidates]")')) {
    check('active candidate blocks deletion until explicitly resolved', await app.evaluate('!document.querySelector("[data-novel-deletion-propose]")'));
    await app.click('[data-novel-deletion-reject-candidates]');
    await app.waitFor('!!document.querySelector("[data-novel-deletion-state=blocked]") && !document.querySelector("[data-novel-deletion-reject-candidates]")', 'candidate blocker resolved');
  }
  check('last scene protection explains how to proceed', await app.evaluate('document.querySelector("[data-novel-deletion-blockers]").textContent.includes("最后一个场景")'));
  await app.click('[data-novel-management-refresh]');
  await app.waitFor('document.querySelector("[data-novel-chapter-management]")?.dataset.novelManagementState==="ready"', 'management refreshed');
  await app.fill('[data-novel-management-input="scene-summary"]', '次要场景');
  await app.click('[data-novel-scene-create]');
  await app.waitFor('document.querySelector("[data-novel-chapter-management]")?.dataset.novelManagementState==="ready"', 'second scene');
  await app.click('[data-novel-deletion-refresh]');
  await app.waitFor('!!document.querySelector("[data-novel-deletion-propose]")', 'last scene blocker resolved');
  await app.click('[data-novel-deletion-propose]');
  await app.waitFor('!!document.querySelector("[data-novel-deletion-pending]")', 'delete gate');
  await app.screenshot('delete-impact-confirmation');
  await app.click('[data-novel-deletion-reject]');
  check('rejecting deletion preserves the scene', (await invoke('novelWorkspace/chapterRead',id,chapterId)).scenes.some(s=>s.id===sceneId));
  const negative = await app.evaluate(`window.novelDesktop.invoke('novel-creation-tool/novelOutlineDetailGeneration/append', ${JSON.stringify([id,{mode:'append-to-selected-beat',beatId:'beat-1',guidance:'x',extra:true}])})`);
  check('newly wired existing method still rejects additive invalid input', negative.ok===false && negative.error.code==='invalid-arguments');
  await writeFile(join(app.evidence, 'validation.json'), JSON.stringify({ iteration: 'I191', scope: 'Production Electron; real CRUD and UI; deterministic HTTP model, strict Main parsing/I11', checks, providerCalls: provider.calls }, null, 2));
  console.log(`I191: ${checks.length} real Electron checks passed`);
} catch (error) {
  await app.screenshot('failure');
  await writeFile(join(app.evidence, 'failure.txt'), await app.evaluate('document.body.innerText'));
  throw error;
} finally { await app.close(); await provider.close(); }
