import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { launchUiElectron } from './ui-electron-session.mjs';
import { uiInvoke } from './ui-test-provider.mjs';
import { startSourceTestProvider, sourceText } from './ui-source-test-provider.mjs';
const provider=await startSourceTestProvider();
provider.state.nullableDeltas=process.env.NOVEL_UI_NULL_DELTAS==='1';
const app=await launchUiElectron(process.env.NOVEL_UI_EVIDENCE ?? 'i194',process.env.NOVEL_UI_EXECUTABLE);
await app.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
const checks=[];
const check=(name,value)=>{assert.ok(value,name);checks.push({name,passed:true});};
const invoke=(method,...args)=>uiInvoke(app,method,...args);
const select=async(selector,value)=>app.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
try {
  await app.fill('[data-novel-project-name-input]','北港作者完整流程');
  await app.click('[data-novel-project-create]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-next-action]")','new work');
  const id=(await invoke('novelWorkspace/projectList'))[0].id;
  // Only service configuration is seeded. Every story layer below comes from the actual author flow.
  await invoke('novelLlmConfig/save',{baseUrl:provider.endpoint,model:'ui-deterministic',apiKey:'test-only-not-a-real-key',maxTokens:32768,thinking:'disabled',reasoningEffort:'low'});
  await app.click('[data-novel-workflow-next-action]');
  await app.fill('[data-novel-source-import-text]',sourceText);
  await app.click('[data-novel-source-import-submit]');
  await app.waitFor('!!document.querySelector("[data-novel-import-interpretation-status=succeeded]")','source classified');
  check('model classification never confirms the source',await app.evaluate('document.querySelector("[data-novel-import-interpretation-confirm]").disabled'));
  await select('[data-novel-import-interpretation-source-role]','background-material');
  await select('[data-novel-import-interpretation-treatment]','adapt-pov');
  const paragraphs=await app.evaluate('[...document.querySelectorAll("[data-novel-import-interpretation-accept]")].map(e=>e.getAttribute("data-novel-import-interpretation-accept"))');
  for(const p of paragraphs) await app.click(`[data-novel-import-interpretation-accept="${p}"]`);
  await app.click('[data-novel-import-interpretation-confirm]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=succeeded]")','rule style generated');
  check('rule style generation is zero write',(await invoke('novelRuleStyleManager/list',id)).rules.length===0);
  await app.screenshot('rule-style-review');
  await app.click('[data-novel-rule-style-import-propose]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=proposed]")','rule style proposed');
  await app.click('[data-novel-rule-style-import-accept]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=applied]")','rule style applied');
  check('rule style requires explicit I11 decision',(await invoke('novelRuleStyleManager/list',id)).rules.length===1);
  provider.state.delay=600;
  await app.click('[data-novel-source-plan-generate]');
  await app.waitFor('!!document.querySelector("[data-novel-source-plan-cancel]")','cancellable source generation');
  await app.click('[data-novel-source-plan-cancel]');
  check('source generation cancellation leaves domain layers empty',(await invoke('novelWorkspace/characterList',id)).length===0);
  provider.state.delay=0;
  await app.click('[data-novel-source-plan-generate]');
  await app.waitFor('!!document.querySelector("[data-novel-source-plan=pending]")','narrative plan generated');
  check('narrative preview is zero write',(await invoke('novelWorkspace/characterList',id)).length===0);
  await app.evaluate('document.querySelector("[data-novel-source-plan]").scrollIntoView({block:"start"})');
  await app.screenshot('source-plan-confirmation');
  await app.click('[data-novel-source-plan-edit]');
  await app.click('[data-novel-back-to-projects]');
  await app.waitFor('!!document.querySelector("[data-novel-leave-confirm]")','plan draft leave protection');
  await app.click('[data-novel-leave-cancel]');
  check('plan editing uses the existing leave gate',await app.evaluate('!!document.querySelector("[data-novel-source-plan-edit-save]")'));
  await app.click('[data-novel-source-plan-edit-save]');
  await app.waitFor('!document.querySelector("[data-novel-source-plan-edit-save]")','unchanged proposal edit');
  check('unchanged plan edit preserves a pending confirmation',await app.evaluate('!!document.querySelector("[data-novel-source-plan=pending]")'));
  await app.send('Page.reload');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-next-action]")','reopen pending plan');
  await app.click('[data-novel-workflow-next-action]');
  await app.waitFor('!!document.querySelector("[data-novel-source-plan=pending]")','durable plan reloaded');
  check('pending source plan resumes from Main checkpoint',true);
  await app.click('[data-novel-source-plan-accept]');
  await app.waitFor('!!document.querySelector("[data-novel-source-plan=applied]")','narrative plan applied');
  check('Main applied all story foundations',(await invoke('novelWorkspace/characterList',id)).length===3);
  check('background chronology did not become canon',(await invoke('novelWorkspace/canonQuery',id,{})).length===0);
  await app.screenshot('source-plan-applied');
  await app.click('[data-novel-source-plan-next]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")','author workflow resumed');
  const pov=(await invoke('novelWorkspace/outlineRead',id)).acts[0].beats[0].detailBeats[0].pov;
  await app.evaluate(`document.querySelectorAll('details[data-novel-nav-group]').forEach(e=>e.open=true)`);
  await app.click('[data-novel-nav-item="chapters"]');
  await app.waitFor('!!document.querySelector("[data-novel-chapter-modes]")', 'chapters');
  await app.click('[data-novel-nav-item="outline"]');
  await app.waitFor('!!document.querySelector("[data-novel-outline-beat]")','outline editing');
  await app.click('[data-novel-outline-beat]');
  await app.click('[data-novel-detail-card="detail-1"]');
  await select('[data-novel-detail-card-editor="detail-1"] select:not([data-novel-entity-select])','writing');
  await app.click('[data-novel-outline-save]');
  await app.waitFor('document.querySelector("[data-novel-outline-save]").disabled && document.body.innerText.includes("已保存")','card writing status saved');
  await app.click('[data-novel-nav-item="chapters"]');
  await app.waitFor('!!document.querySelector("[data-novel-chapter-mode=materials]")','return to bound scene');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.waitFor('document.querySelector("[data-novel-chapter-management]")?.dataset.novelManagementState==="ready"', 'management ready');
  await app.fill('[data-novel-management-input="chapter-title"]', '雨夜的北港与未完成的海图');
  await app.evaluate(`(() => { const e=document.querySelector('[data-novel-entity-select="chapter-pov"]'); if(e){e.value=${JSON.stringify(pov)};e.dispatchEvent(new Event('change',{bubbles:true}));} })()`);
  await app.click('[data-novel-chapter-create]');
  await app.waitFor('!!document.querySelector("[data-novel-chapter-item]")', 'chapter created');
  await app.click('[data-novel-chapter-item]');
  await app.click('[data-novel-chapter-mode="candidate"]');
  await app.click('[data-novel-candidate-propose-continue]');
  await app.waitFor('!!document.querySelector("[data-novel-candidate-review], [data-novel-candidate-error]")', 'candidate result');
  check('real Main provider pipeline produces review', await app.evaluate('!!document.querySelector("[data-novel-candidate-review]")'));
  await app.screenshot('candidate-review');
  await app.click('[data-novel-candidate-adopt-draft]');
  await app.waitFor('document.querySelector("[data-novel-writing-workflow-state=saved]")!==null', 'draft accepted');
  check('scene navigation is nested within the chapter tree', await app.evaluate('!!document.querySelector("[data-novel-chapter-tree] [data-novel-chapter-scenes] [data-novel-scene-item]")'));
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.click('[data-novel-management-refresh]');
  await app.waitFor('document.querySelector("[data-novel-chapter-management]")?.dataset.novelManagementState==="ready"','binding choices');
  await select('[data-novel-entity-select="binding-target"]','detail-1');
  await app.click('[data-novel-binding-save]');
  await app.waitFor('document.querySelector("[data-novel-binding-state]").textContent.includes("手动绑定 1")','scene bound');
  const beforeCompletion=await invoke('novelReview/bookReadiness',id,{offset:0,limit:64});
  check('publication remains blocked before card completion',!beforeCompletion.gateOpen);
  await app.click('[data-novel-chapter-mode="candidate"]');
  await app.fill('[data-novel-candidate-rewrite-prompt]','保留事实，精炼当前已绑定场景的正文。');
  await app.click('[data-novel-candidate-propose-rewrite]');
  await app.waitFor('!!document.querySelector("[data-novel-candidate-adopt-draft]")','bound revision candidate');
  await app.click('[data-novel-candidate-adopt-draft]');
  await app.waitFor('!!document.querySelector("[data-novel-writing-workflow-state=saved]")','bound revision adopted');
  await app.click('[data-novel-chapter-mode="writing"]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-prepare]")', 'finalization');
  await app.click('[data-novel-finalization-prepare]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-propose], [data-novel-finalization-message]")', 'finalization analysis');
  await app.click('[data-novel-finalization-propose]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-pending]")', 'confirmation gate');
  await app.screenshot('finalization-confirmation');
  await app.click('[data-novel-finalization-accept]');
  await app.waitFor('!!document.querySelector("[data-novel-finalization-complete]")', 'finalization applied');
  check('candidate adoption and separate I11 finalization complete', await app.evaluate('document.querySelector("[data-novel-writing-workflow]").textContent.includes("当前正文已定稿") && !document.querySelector("[data-novel-writing-workflow]").textContent.includes("草稿已保存")'));
  await app.screenshot('finalization-complete');
  await app.click('[data-novel-nav-item="review"]');
  await app.click('[data-novel-review-refresh]');
  await app.waitFor('!!document.querySelector("[data-novel-book-readiness-refresh]")','review completed');
  await app.click('[data-novel-book-readiness-refresh]');
  await app.waitFor('!!document.querySelector("[data-novel-book-release-gate=open]")','completed book release gate');
  await app.screenshot('book-ready');
  await app.click('[data-novel-nav-item="importExport"]');
  await app.waitFor('!!document.querySelector("[data-novel-ie-compile]")','export workspace');
  const manuscript=await invoke('novelImportExport/compileManuscript',id,{format:'txt'});
  check('real Main compiles the authored chapters and scenes',manuscript.sceneCount===1 && manuscript.content.includes('铜钥匙'));
  await writeFile(join(app.evidence,'author-manuscript.txt'),manuscript.content);
  await app.screenshot('author-export');
  await app.click('[data-novel-back-to-projects]');
  await app.waitFor('!!document.querySelector("[data-novel-project-new]")','return to library');
  await app.click('[data-novel-project-new]');
  await app.fill('[data-novel-project-name-input]','普通大纲来源验收');
  await app.click('[data-novel-project-create]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-next-action]")','ordinary work');
  await app.click('[data-novel-workflow-next-action]');
  await app.fill('[data-novel-source-import-text]',sourceText);
  await app.click('[data-novel-source-import-submit]');
  await app.waitFor('!!document.querySelector("[data-novel-import-interpretation-status=succeeded]")','ordinary source');
  await select('[data-novel-import-interpretation-source-role]','synopsis');
  await select('[data-novel-import-interpretation-treatment]','expand-outline');
  const retained=await app.evaluate('[...document.querySelectorAll("[data-novel-import-interpretation-accept]")].map(e=>e.getAttribute("data-novel-import-interpretation-accept"))');
  for(const p of retained) await app.click(`[data-novel-import-interpretation-accept="${p}"]`);
  await app.click('[data-novel-import-interpretation-confirm]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=succeeded]")','ordinary rules');
  await app.click('[data-novel-rule-style-import-propose]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=proposed]")','ordinary rules proposal');
  await app.click('[data-novel-rule-style-import-accept]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=applied]")','ordinary rules accepted');
  provider.state.delay=600;
  await app.click('[data-novel-source-plan-generate]');
  await app.waitFor('!!document.querySelector("[data-novel-analysis-cancel]")','ordinary analysis starts');
  await app.click('[data-novel-analysis-cancel]');
  await app.waitFor('!!document.querySelector("[data-novel-analysis-retry]")','ordinary analysis cancelled');
  provider.state.delay=0;
  await app.click('[data-novel-analysis-retry]');
  await app.waitFor('!!document.querySelector("[data-novel-onboarding-apply]")','ordinary candidates');
  check('ordinary candidate preview blocks apply before decisions',await app.evaluate('document.querySelector("[data-novel-onboarding-apply]").disabled'));
  await app.evaluate('document.querySelectorAll(".nv-onboarding__layer-details").forEach(e=>e.open=true)');
  await app.click('[data-novel-onboarding-verdict=characters][data-novel-onboarding-decision=edit]');
  await app.click('[data-novel-onboarding-edit-cancel=characters]');
  await app.click('[data-novel-onboarding-verdict=characters][data-novel-onboarding-decision=regenerate]');
  await app.click('[data-novel-onboarding-regenerate-cancel=characters]');
  await app.click('[data-novel-onboarding-verdict=characters][data-novel-onboarding-decision=regenerate]');
  await app.click('[data-novel-onboarding-regenerate-confirm=characters]');
  await app.waitFor('!!document.querySelector("[data-novel-onboarding-verdict=characters][data-novel-onboarding-decision=edit]")','ordinary layer regenerated');
  for(const layer of ['characters','worldview','outline','relationship','state','canon']) {
    await app.evaluate(`document.querySelector('[data-novel-onboarding-layer="${layer}"] details').open=true`);
    await app.click(`[data-novel-onboarding-verdict="${layer}"][data-novel-onboarding-decision="accept"]`);
  }
  await app.waitFor('!document.querySelector("[data-novel-onboarding-apply]").disabled','ordinary decisions complete');
  await app.screenshot('ordinary-candidate-decisions');
  await app.click('[data-novel-onboarding-apply]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")','ordinary apply');
  const ordinaryId=(await invoke('novelWorkspace/projectList')).find(p=>p.id!==id).id;
  check('ordinary source reaches existing six-layer apply',(await invoke('novelWorkspace/characterList',ordinaryId)).length===2);
  await app.screenshot('ordinary-complete');
  check('ordinary import yields readable writing context',(await invoke('novelAssistant/context',ordinaryId)).characters===2);
  await writeFile(join(app.evidence,'validation.json'),JSON.stringify({iteration:'I194',checks,providerCalls:provider.calls},null,2));
  console.log(`I194: ${checks.length} real Electron author-flow checks passed`);
} catch(error) {
  await app.screenshot('failure');await writeFile(join(app.evidence,'failure.txt'),await app.evaluate('document.body.innerText'));await writeFile(join(app.evidence,'provider-calls.json'),JSON.stringify(provider.calls,null,2));throw error;
} finally {await app.close();await provider.close();}
