import assert from 'node:assert/strict';
import { writeFile,readFile } from 'node:fs/promises';
import { join,resolve } from 'node:path';
import { launchUiElectron } from './ui-electron-session.mjs';
import { startUiTestProvider,uiInvoke } from './ui-test-provider.mjs';
const prompts=[];const provider=await startUiTestProvider(prompt=>{if(!prompt.startsWith('你是长篇小说章节写作器。')&&!prompt.startsWith('你是长篇小说续写 agent。'))return undefined;prompts.push(prompt);return {kind:'prose',output:'调查员沿着主街前进，收起录音笔。'};});
const packaged=process.argv.includes('--packaged');
const app=await launchUiElectron(packaged?'i222-packaged':'i222',packaged?resolve('artifacts/desktop/i222-release/win-unpacked/Novel Creation Tool.exe'):undefined);
const invoke=(method,...args)=>uiInvoke(app,method,...args);
try{
 await app.fill('[data-novel-project-name-input]','新章节写作恢复');await app.click('[data-novel-project-create]');await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")','project');const id=(await invoke('novelWorkspace/projectList'))[0].id;
 await invoke('novelLlmConfig/save',{baseUrl:provider.endpoint,model:'ui-deterministic',apiKey:'test-only-not-a-real-key',maxTokens:32768,thinking:'disabled',reasoningEffort:'low'});
 const role={name:'调查员',aliases:[],kind:'protagonist',personality:'谨慎',background:'民俗调查员',motivation:'查访',goals:[],flaws:[],abilities:[],speechStyle:'克制',staticTraits:[],arc:{startingPoint:'',desiredEnd:'',keyBeats:[]},relationships:[],knowledgeIds:[]};
 for(const characterId of ['old-investigator','hero'])await invoke('novelWorkspace/characterCreate',id,{...role,id:characterId});
 const outline={id:'outline',structure:'free',logline:'调查',themes:[],acts:[{id:'act',index:0,title:'抵达',goal:'调查',beats:[{id:'beat',title:'初识',description:'调查主街',charactersInvolved:['old-investigator'],conflictType:'external',prerequisites:[],optional:false,detailBeats:[{id:'first',title:'已经写过',summary:'抵达巴士站',pov:'old-investigator',wordTarget:100,points:[],status:'writing'},{id:'next',title:'主街调查',summary:'沿主街查访',pov:'old-investigator',wordTarget:100,points:['记录主街'],status:'planned'}]}]}],foreshadowing:[],endings:[]};
 await invoke('novelWorkspace/outlineSave',id,outline);await invoke('novelRuleStyleManager/saveStyle',id,{name:'克制',person:'third-limited',tense:'past',povScope:'single',tone:'克制',proseStyle:'简洁',chapterFormat:'plain',dialogueConventions:'quotes',forbidden:[]});await invoke('novelRuleStyleManager/createRule',id,{id:'rule',scope:'global',kind:'genre',statement:'遵循已知事实。',priority:1,immutable:false,examples:[],active:true});
 const directory=join(app.profile,'library',id);await writeFile(join(directory,'knowledge.yaml'),JSON.stringify({entries:[],states:[{characterId:'old-investigator',knows:[]},{characterId:'hero',knows:[]}]}));await writeFile(join(directory,'outline-progress.yaml'),JSON.stringify({outlineId:'outline',currentAct:'act',currentBeat:'beat',completedBeats:[],deviations:[],tensionLevel:0}));
 let result=await invoke('novelText/chapterCreate',id,{id:'chapter',index:1,title:'第一章',pov:'old-investigator',status:'draft',expectedFingerprint:(await invoke('novelText/fingerprint',id)).fingerprint});
 await invoke('novelText/sceneCreate',id,{chapterId:'chapter',index:0,scene:{id:'saved',content:'此前结尾：调查员已经离开巴士站。',summary:'抵达',beats:[],canonEvents:[],notes:''},expectedFingerprint:result.fingerprint});await invoke('novelSceneOutlineBinding/save',id,{sceneId:'saved',detailBeatId:'first',expectedFingerprint:(await invoke('novelSceneOutlineBinding/read',id)).fingerprint});
 const merge=await invoke('novelWorkspace/characterMergePropose',{projectId:id,sourceId:'old-investigator',targetId:'hero',fields:[],stateFrom:'target',knowledgeFrom:'target'});await invoke('novelWorkspace/characterMergeDecide',{projectId:id,proposalId:merge.proposalId,accept:true});
 // Isolated fixture recreates a stale pre-merge editor writing its B5 document.
 await writeFile(join(directory,'outline.yaml'),JSON.stringify({...outline,version:1}));await app.send('Page.reload');await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")','reload');await app.click('[data-novel-nav-group="advanced"] > summary');await app.click('[data-novel-nav-item="chapters"]');await app.waitFor('!!document.querySelector("[data-novel-chapter-item]")','chapter');await app.click('[data-novel-chapter-item]');await app.click('[data-novel-chapter-mode="materials"]');await app.waitFor('!!document.querySelector("[data-novel-management-state=ready]")','management');
 await app.fill('[data-novel-management-input="chapter-title"]','第二章');await app.click('[data-novel-chapter-create]');await app.waitFor('document.querySelector("[data-novel-management-message]")?.textContent.includes("章节已创建")','new chapter');const chapters=await invoke('novelWorkspace/chapterList',id);assert.equal(chapters.length,2);const newChapter=chapters.find(chapter=>chapter.id!=='chapter');await app.click('[data-novel-chapter-item="'+newChapter.id+'"]');
 await app.click('[data-novel-chapter-mode="candidate"]');const before=(await invoke('novelText/fingerprint',id)).fingerprint;
 for(const intent of ['continue','scene-card']){await app.click(`[data-novel-candidate-propose-${intent}]`);await app.waitFor('!!document.querySelector("[data-novel-candidate-state=ready], [data-novel-candidate-state=error]")','candidate');assert.equal(await app.evaluate('document.querySelector("[data-novel-candidate-state=error]")?.textContent??null'),null);await app.screenshot('new-chapter-'+intent);await app.click('[data-novel-candidate-reject]');await app.waitFor('!!document.querySelector("[data-novel-candidate-state=done]")','rejected');}
 assert.equal(prompts.length,2);for(const prompt of prompts){assert.ok(prompt.includes('主街调查'));assert.ok(prompt.includes('此前结尾'));assert.ok(!prompt.includes('old-investigator'));}assert.equal((await invoke('novelText/fingerprint',id)).fingerprint,before);
 assert.ok((await readFile(join(directory,'outline.yaml'),'utf8')).includes('old-investigator'));const saved=await invoke('novelWorkspace/outlineSave',id,outline);assert.equal(saved.acts[0].beats[0].detailBeats[1].pov,'hero');saved.acts[0].beats[0].detailBeats[1].status='done';await invoke('novelWorkspace/outlineSave',id,saved);for(const intent of ['continue','scene-card'])await assert.rejects(invoke('novelWriting/proposeAt',id,{intent,chapterId:newChapter.id,sceneId:'exhausted-'+intent},undefined),/新增待写场景卡/);assert.equal(prompts.length,2);
 await writeFile(join(app.evidence,'validation.json'),JSON.stringify({iteration:'I222',packaged,newChapterViaUi:true,bothIntents:true,nextUnboundCard:true,mergedIdentity:true,priorChapterHistory:true,zeroProseWrites:true,staleSaveNormalized:true},null,2));process.stdout.write('I222 Electron: create chapter after existing scene, both writing intents, completed identity mapping, next unbound card and unchanged prose passed\n');
}finally{await app.close();await provider.close();}
