import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { launchUiElectron } from './ui-electron-session.mjs';
import { uiInvoke } from './ui-test-provider.mjs';

const app = await launchUiElectron('i209');
const invoke = (method, ...args) => uiInvoke(app, method, ...args);
const title = '[data-novel-management-input="chapter-title"]';
const pov = '[data-novel-entity-select="chapter-pov"]';
try {
  await app.fill('[data-novel-project-name-input]', '章节信息保存验收');
  await app.click('[data-novel-project-create]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")', 'project');
  const id = (await invoke('novelWorkspace/projectList'))[0].id;
  for (const character of ['hero', 'other']) await invoke('novelWorkspace/characterCreate', id, { id: character, name: character === 'hero' ? '主角' : '同伴', aliases: [], kind: 'protagonist', personality: '', background: '', motivation: '', goals: [], flaws: [], abilities: [], speechStyle: '', staticTraits: [], arc: { startingPoint: '', desiredEnd: '', keyBeats: [] }, relationships: [], knowledgeIds: [] });
  const { fingerprint } = await invoke('novelText/fingerprint', id);
  const created = await invoke('novelText/chapterCreate', id, { id: 'chapter', index: 1, title: '旧标题', pov: 'hero', status: 'revised', expectedFingerprint: fingerprint });
  await invoke('novelText/sceneCreate', id, { chapterId: 'chapter', index: 0, scene: { id: 'scene', content: '窗外下着雨。', summary: '', beats: [], canonEvents: [], notes: '' }, expectedFingerprint: created.fingerprint });
  const before = await invoke('novelWorkspace/chapterRead', id, 'chapter');
  const beforeScene = await invoke('novelWorkspace/sceneRead', id, 'chapter', 'scene');
  await app.send('Page.reload');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-panel]")', 'reopen');
  await app.click('[data-novel-nav-group="advanced"] > summary');
  await app.click('[data-novel-nav-item="chapters"]');
  await app.waitFor('!!document.querySelector("[data-novel-chapter-item]")', 'chapter list');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.waitFor('!!document.querySelector("[data-novel-management-state=ready]")', 'management');
  await app.click('[data-novel-chapter-update]');
  await app.waitFor('document.querySelector("[data-novel-management-message]")?.textContent.includes("选择要修改的章节")', 'missing chapter');
  await app.click('[data-novel-chapter-item]');
  await app.waitFor('!!document.querySelector("[data-novel-scene-item]")', 'chapter loaded');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.waitFor('!!document.querySelector("[data-novel-management-state=ready]")', 'ready');
  assert.equal(await app.evaluate(`document.querySelector('${title}').value`), '旧标题');
  assert.equal(await app.evaluate(`document.querySelector('${pov}').value`), 'hero');
  await app.evaluate(`document.querySelector('${title}').select()`);
  await app.fill(title, '雨夜调查');
  await app.evaluate(`(() => { const e=document.querySelector('${pov}'); e.value='other'; e.dispatchEvent(new Event('change',{bubbles:true})); })()`);
  await app.click('[data-novel-chapter-mode="candidate"]');
  await app.click('[data-novel-chapter-mode="materials"]');
  await app.waitFor('!!document.querySelector("[data-novel-management-state=ready]")', 'mode returned');
  assert.equal(await app.evaluate(`document.querySelector('${title}').value`), '雨夜调查');
  await app.click('[data-novel-chapter-update]');
  await app.waitFor('document.querySelector("[data-novel-management-message]")?.textContent.includes("章节信息已保存")', 'saved');
  await invoke('novelWorkspace/projectOpen', id);
  const saved = await invoke('novelWorkspace/chapterRead', id, 'chapter');
  assert.equal(saved.title, '雨夜调查'); assert.equal(saved.pov, 'other'); assert.equal(saved.status, 'revised');
  assert.deepEqual(saved.scenes, before.scenes);
  assert.deepEqual((await invoke('novelWorkspace/sceneRead', id, 'chapter', 'scene')).scene, beforeScene.scene);
  await app.screenshot('chapter-saved');
  await app.click('[data-novel-chapter-create]');
  await app.waitFor('document.querySelector("[data-novel-management-message]")?.textContent.includes("章节已创建")', 'new independent chapter');
  const chapters = await invoke('novelWorkspace/chapterList', id);
  assert.equal(chapters.length, 2);
  assert.equal(new Set(chapters.map(chapter => chapter.id)).size, 2);
  assert.equal(chapters.find(chapter => chapter.id !== 'chapter').index, 2);
  await writeFile(join(app.evidence, 'validation.json'), JSON.stringify({ passed: true, checks: ['missing chapter has feedback', 'selected metadata fills title and POV', 'mode changes preserve edits', 'saved metadata survives repository reopen', 'scene text and revised status unchanged', 'create after edit uses independent ID and index'] }, null, 2));
  process.stdout.write('I209 Electron: chapter metadata fills, saves, reopens and preserves prose; independent creation passed\n');
} finally { await app.close(); }
