import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { launchUiElectron } from './ui-electron-session.mjs';
import { uiInvoke } from './ui-test-provider.mjs';
import { startSourceTestProvider, sourceText } from './ui-source-test-provider.mjs';

const provider = await startSourceTestProvider();
const app = await launchUiElectron('i201');
const invoke = (method, ...args) => uiInvoke(app, method, ...args);
const select = (selector, value) => app.evaluate(`(() => {const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
const ruleCalls = () => provider.calls.filter(call => call.kind === 'rule-style').length;
try {
  await app.fill('[data-novel-project-name-input]', '确认后重新生成');
  await app.click('[data-novel-project-create]');
  await app.waitFor('!!document.querySelector("[data-novel-workflow-next-action]")', 'project');
  const id = (await invoke('novelWorkspace/projectList'))[0].id;
  await invoke('novelLlmConfig/save', { baseUrl: provider.endpoint, model: 'ui-deterministic', apiKey: 'test-only-not-a-real-key', maxTokens: 32768, thinking: 'disabled', reasoningEffort: 'low' });
  // Seed a genuinely non-first import with existing B1/B4 through the production IPC owners.
  await invoke('novelRuleStyleManager/createRule', id, { id: 'old-rule', scope: 'global', kind: 'magic', statement: '原规则必须保留到最终确认', priority: 80, immutable: true, examples: [], active: true });
  await invoke('novelRuleStyleManager/saveStyle', id, { name: '原文风', person: 'third-limited', tense: 'past', povScope: 'single', tone: '原语气', proseStyle: '原表达', chapterFormat: '分章', dialogueConventions: '引号', forbidden: [] });
  const before = await invoke('novelRuleStyleManager/list', id);
  const input = { projectId: id, sourceHash: 'a'.repeat(64), intent: { sourceRole: 'idea', treatment: 'expand-outline' }, paragraphDecisions: [{ paragraphId: 'paragraph-0001', role: 'plot-plan', decision: 'accepted', summary: '旧来源' }] };
  const first = await invoke('novelImportInterpretation/create', input);
  await invoke('novelImportInterpretation/confirm', { ...input, importSessionId: first.importSessionId });
  await app.click('[data-novel-workflow-next-action]');
  await app.fill('[data-novel-source-import-text]', sourceText);
  await app.click('[data-novel-source-import-submit]');
  await app.waitFor('!!document.querySelector("[data-novel-import-interpretation-status=succeeded]")', 'source');
  await select('[data-novel-import-interpretation-source-role]', 'background-material');
  await select('[data-novel-import-interpretation-treatment]', 'adapt-pov');
  const paragraphs = await app.evaluate('[...document.querySelectorAll("[data-novel-import-interpretation-accept]")].map(e=>e.getAttribute("data-novel-import-interpretation-accept"))');
  for (const p of paragraphs) await app.click(`[data-novel-import-interpretation-accept="${p}"]`);
  await app.click('[data-novel-import-interpretation-confirm]');
  await app.waitFor('document.querySelector("[data-novel-rule-style-import]")?.textContent.includes("此作品此前已确认过导入")', 'first-import refusal');
  await app.click('[data-novel-rule-style-regenerate]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-regeneration-confirmation]")', 'replacement scope');
  assert.equal(ruleCalls(), 0); assert.deepEqual(await invoke('novelRuleStyleManager/list', id), before);
  await app.screenshot('replacement-scope');
  await app.click('[data-novel-rule-style-regenerate-reject]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-regenerate]")', 'rejected scope');
  assert.equal(ruleCalls(), 0); assert.deepEqual(await invoke('novelRuleStyleManager/list', id), before);
  await app.click('[data-novel-rule-style-regenerate]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-regenerate-confirm]")', 'new scope');
  await app.click('[data-novel-rule-style-regenerate-confirm]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=succeeded]")', 'regenerated candidate');
  assert.equal(ruleCalls(), 1); assert.deepEqual(await invoke('novelRuleStyleManager/list', id), before);
  await app.click('[data-novel-rule-style-import-propose]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=proposed]")', 'candidate confirmation');
  assert.deepEqual(await invoke('novelRuleStyleManager/list', id), before);
  await app.click('[data-novel-rule-style-import-accept]');
  await app.waitFor('!!document.querySelector("[data-novel-rule-style-import-status=applied]")', 'replaced');
  const after = await invoke('novelRuleStyleManager/list', id);
  assert.equal(after.rules.some(rule => rule.id === 'old-rule'), false);
  assert.equal(after.rules.length, 1); assert.notEqual(after.style.name, before.style.name);
  assert.equal((await invoke('novelWorkspace/characterList', id)).length, 0);
  await app.screenshot('replacement-applied');
  await writeFile(join(app.evidence, 'validation.json'), JSON.stringify({ iteration: 'I201', laterImport: true, existingRulesAndStyle: true, scopeGate: true, rejectedScopeNoLlm: true, candidateGate: true, unchangedUntilAccept: true, replaced: true, llmCalls: ruleCalls(), otherLayersUntouched: true }, null, 2));
  process.stdout.write('I201 Electron: later import + existing B1/B4, rejected scope zero LLM, two Gates, replacement only after candidate accept passed\n');
} finally { await app.close(); await provider.close(); }
