/**
 * I52/I53 onboarding 合同兼容入口（I102 拆分，计划 §18 I102）：绑定基座
 * （onboarding-binding.ts）、analysis 合同（onboarding-analysis.ts）与
 * adjudication 合同（onboarding-adjudication.ts）经本 index 统一重导出，
 * 外部调用方符号入口不变。
 */
export {
  onboardingBindingSchema,
  onboardingLayerSchema,
  onboardingProjectIdSchema,
  onboardingSessionIdSchema,
  sourceHashSchema,
  type OnboardingBinding,
  type OnboardingLayerId,
} from './onboarding-binding.js';
export {
  evidenceAtomSchema,
  evidenceMapSchema,
  layerCandidatesSchema,
  ONBOARDING_LAYER_KEYS,
  onboardingAnalysisBeginResultSchema,
  onboardingAnalysisInputSchema,
  onboardingAnalysisOutputSchema,
  onboardingAnalysisResultSchema,
  onboardingAnalysisStartInputSchema,
  onboardingAnalysisStatusSchema,
  onboardingCanonLayerSchema,
  onboardingCanonSchema,
  onboardingCharacterLayerSchema,
  onboardingCharacterSchema,
  onboardingLayersSchema,
  onboardingOutlineLayerSchema,
  onboardingOutlineSchema,
  onboardingRelationshipLayerSchema,
  onboardingRelationshipSchema,
  onboardingSessionSchema,
  onboardingStateLayerSchema,
  onboardingStateSchema,
  onboardingWorldviewLayerSchema,
  onboardingWorldviewSchema,
  type CandidateConfidence,
  type EvidenceAtom,
  type EvidenceMap,
  type OnboardingAnalysisBeginResult,
  type OnboardingAnalysisInput,
  type OnboardingAnalysisOutput,
  type OnboardingAnalysisResult,
  type OnboardingAnalysisStartInput,
  type OnboardingAnalysisStatus,
  type OnboardingCanon,
  type OnboardingCharacter,
  type OnboardingLayerKey,
  type OnboardingLayers,
  type OnboardingOutline,
  type OnboardingRelationship,
  type OnboardingSession,
  type OnboardingState,
  type OnboardingWorldview,
} from './onboarding-analysis.js';
export {
  onboardingAcceptedLayerSchema,
  onboardingAdjudicateInputSchema,
  onboardingApplyResultSchema,
  onboardingCandidateProvenanceSchema,
  onboardingFinalApplyInputSchema,
  onboardingLayerDecisionRequirementSchema,
  onboardingLayerProposalPayloadSchema,
  onboardingProposalModeSchema,
  type OnboardingAcceptedLayer,
  type OnboardingAdjudicateInput,
  type OnboardingApplyResult,
  type OnboardingCandidateProvenance,
  type OnboardingFinalApplyInput,
  type OnboardingLayerDecision,
  type OnboardingLayerProposalPayload,
  type OnboardingProposalMode,
} from './onboarding-adjudication.js';
